
Category.create(name: "Tシャツ")
Category.create(name: "タオル")
Category.create(name: "バッジ")
Category.create(name: "アクリルキー")
Category.create(name: "ステッカー")
Category.create(name: "ポスター")
Category.create(name: "リストバンド")
Category.create(name: "うちわ")
Category.create(name: "チェキ")
Category.create(name: "写真")
Category.create(name: "ペンライト")
Category.create(name: "CD")
Category.create(name: "DVD")
Category.create(name: "その他")
